### ISSUE TITLE
Can't load the mod

### ISSUE THREAD

**Issue by SnowedInOwl** [Syconn/StarForge#5]
So I'm trying to load the game with just StarForge and it just gives me a load mod error

don't if I'm missing a dependence or something else is wrong

Crash log: 
[crash-2022-07-23_16.00.54-fml.txt](https://github.com/Syconn/StarForge/files/9174646/crash-2022-07-23_16.00.54-fml.txt)

Debug Log File:
[debug.log](https://github.com/Syconn/StarForge/files/9174649/debug.log)

Log File:
[latest.log](https://github.com/Syconn/StarForge/files/9174650/latest.log)

**Comment by Syconn** [comment]
I believe it becuase your running 1.18.2, try 1.18 or 1.18.1
